version: "3.8"

services:
  db:
    image: mysql:8.0.23
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    container_name: db
    restart: always

  server:
    env_file:
      - ./.env
    build: ./packages/server
    container_name: server
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      WAIT_HOSTS: db:3306
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/usr/src/app
      - /usr/src/app/node_modules

  web:
    env_file:
      - ./.env
    build: ./packages/web
    container_name: web
    depends_on:
      - server
    ports:
      - "4000:4000"
    volumes:
      - ./packages/web:/usr/src/app
      - /usr/src/app/node_modules

  items-manager:
    image: items-manager:1.0.0
    build: .
    container_name: items-manager
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - .:/www
